name: Docker

on:
  schedule:
    - cron: '24 1 * * 1'
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ github.repository }}
      - name: tags
        run: echo ${{ github.ref_name }}
      #- name: Checkout
      #  uses: actions/checkout@v4
      #- name: Log in to Docker
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ${{ env.REGISTRY }}
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #- name: Build and push
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: true
      #    tags: ${{ env.IMAGE_NAME }}
